[build]
  command = "npm run build"
  publish = "dist"

# Redirección para el SPA (manejo de rutas)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirección HTTPS + www (opcional, si ya está en _redirects)
[[redirects]]
  from = "http://todomampara.com/*"
  to = "https://www.todomampara.com/:splat"
  status = 301
  force = true